Project.Web/Areas/AreaIndex/Controllers/MenuController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Project.Entity;
using Project.Repository.Persistence;
using Project.Web.Areas.AreaIndex.Models;
using System.Linq;

namespace Project.Web.Areas.AreaIndex.Controllers
{
    [Authorize]
    public class MenuController : Controller
    {

        public ActionResult PopularMenu(ICollection<Menu> menus)
        {
            return PartialView("_menu", menus);
        }

    }
}

Project.Web/Views/_dropdownGrupo.cshtml
<script type="text/javascript">
    $(document).ready(function () {
        PopulaSelectListId("Lista", "Grupo", "#drpGrupoNivel_1", "-1", null);
        $("#drpGrupoNivel_2").prop("disabled", "disabled");

        $("#drpGrupoNivel_1").change(function () {
            $("#drpGrupoNivel_2").prop("disabled", "disabled");

            var id = $(this).val();
            PopulaSelectListId("Lista", "Grupo", "#drpGrupoNivel_2", "-1", id);

            $("#drpGrupoNivel_2").prop("disabled", false);
        });
    })
</script>
<div class="col-3">
    <label>Grupo:</label><br />
    <select id="drpGrupoNivel_1" class="form-control"></select>
</div>
<div class="col-3">
    <label>Sub-Grupo:</label><br />
    <select id="drpGrupoNivel_2" class="form-control"></select>
</div>

Project.Web/Views/_dropdownTipoItemConta.cshtml
<script type="text/javascript">
    $(document).ready(function () {
        PopulaSelectList("Lista", "TipoItemConta", "#drpTipoItemConta", "-1");
    })
</script>
<div class="col-3">
    <label>Tipo:</label><br />
    <select id="drpTipoItemConta" class="form-control"></select>
</div>

Project.Web/Views/_edicaoGeneric.cshtml
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title"><span id="spTitle"></span></h5>

            <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">×</span>
                <span class="sr-only">Close</span>
            </button>

        </div>
        <div class="modal-body">

            <input type="hidden" id="txtId" value="@ViewBag.Id" />

            <div class="row">
                <div class="col-12">
                    <label><span id="spLabel"></span></label>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <input type="text" id="txtDescricao" value="@ViewBag.Descricao" class="form-control" />
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <label>Status:</label>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <select id="cmbStatusEdicao" class="form-control"></select>
                    <input type="hidden" id="txtStatus" value="@ViewBag.Status" />
                </div>
            </div>
            <div id="alertEdicao" class="row mt-2" style="display:none">
                <div class="col-12">
                    <div class="alert alert-primary" role="alert">
                        <span id="spEdicaoMsg"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <input type="button" class="btn btn-outline-dark" id="btnSalvar" value="Salvar" onclick="editar()" />
            <input type="button" class="btn btn-outline-dark" value="Cancelar" data-dismiss="modal" />
        </div>
    </div>
</div>

Project.Web/Views/_inclusaoGeneric.cshtml
<div class="modal-dialog">
    <div class="modal-content">

        <div class="modal-header">
            <h5 class="modal-title"><span id="spTitle"></span></h5>

            <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">×</span>
                <span class="sr-only">Close</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-12">
                    <label><span id="spLabel"></span></label>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <input type="text" id="txtDescricao" class="form-control" />
                </div>
            </div>

            <div id="alertInclusao" class="row mt-2" style="display:none">
                <div class="col-12">
                    <div class="alert alert-primary" role="alert">
                        <span id="spInclusaoMsg"></span>
                    </div>
                </div>
            </div>

        </div>
        <div class="modal-footer">
            <input type="button" id="btnSalvar" value="Salvar" onclick="Incluir()" class="btn btn-outline-dark" />
            <input type="button" value="Cancelar" class="btn btn-outline-dark" data-dismiss="modal" />
        </div>
    </div>
</div>

Project.Web/Views/_layout.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--Não guardar cache-->
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />

    <title>@ViewBag.Title - Conta Fácil</title>

    <link href="~/css/bootstrap.min.css" rel="stylesheet" />

    <!--style para uso de paginação via PagedList-->
    <link href="~/css/PagedList.css" rel="stylesheet" />


    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/css/jquery.dataTables.min.css" rel="stylesheet" />

    @*<link href="~/css/Site.css" rel="stylesheet" />*@

    <script src="~/js/jquery-3.0.0.min.js"></script>
    <!--js para realizar validação no AjaxBeginForm-->
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/jquery.validate.unobtrusive.js"></script>

    <!--js para realizar execução do evento no javascritp OnSuccess no AjaxBeginForm e capturar a mensagem no js-->
    <script src="~/js/jquery.unobtrusive-ajax.min.js"></script>


    <!--js do Bootstrap para corrigir o erro no dropdown-->
    <script src="~/js/bootstrap.bundle.min.js"></script>

    <!--js do DataTable JQuery para paginação-->
    <script src="~/Scripts/jquery.dataTables.min.js"></script>


    <script src="~/js/site.js"></script>


    <style type="text/css">

        .progresso {
            display: none;
            position: fixed;
            padding-top: 50%;
            padding-left: 50%;
            vertical-align: middle;
            text-align: center;
            font-size: 16px;
            background-color: white;
            height: 100%;
            width: 100%;
            filter: alpha(opacity=70);
            opacity: 0.7;
        }

        #imgCarregando {
            width: 100px;
            height: 100px;
            display: block;
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
            z-index: 2;
        }
    </style>
</head>
<body>
    @Html.Partial("~/Views/_navbar.cshtml")

    <img id="imgCarregando" src="~/assets/gifs/loading.gif" style="display:block" />

    <div id="divBody" class="container mt-2" style="z-index:1; display:none">
        @RenderBody()
    </div>



    <div id="modalMensagem" class="modal fade" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Sr. Usuário</h4>
                    <span style="font-size:xx-large"><i class="fa fa-info-circle"></i></span>
                </div>
                <div class="modal-body">
                    <p><span id="modalMensagemId"></span></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-dark btn-sm" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modalConfirmMensagem" class="modal fade" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Sr. Usuário</h4>
                    <span style="font-size:xx-large"><i class="fa fa-info-circle"></i></span>
                </div>
                <div class="modal-body">
                    <p><span id="spanConfirmMensagem"></span></p>
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-outline-dark active" id="btnConfirmSim">Sim</button>
                    <button type="button" data-dismiss="modal" class="btn btn-outline-dark">Não</button>
                </div>
            </div>
        </div>
    </div>

    @*<div id="divCarregando" class="progresso">
            <br />
            <img src="~/assets/gifs/ajax-loader.gif" />
            <br />
            Carregando...
        </div>*@

</body>
</html>

Project.Web/Views/_modalCrud-Lg.cshtml
<!--Para que a validação do MVC funcione, foi necessário colocar a referência deste script-->
<script src="~/js/jquery.validate.unobtrusive.min.js"></script>

<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">@ViewBag.Titulo</h5>
            <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">×</span>
                <span class="sr-only">Close</span>
            </button>
        </div>
        @RenderBody()
    </div>
</div>

Project.Web/Views/_modalCrud.cshtml
<div class="modal-dialog">
    <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@ViewBag.Titulo</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                    <span class="sr-only">Close</span>
                </button>
            </div>
            <div class="modal-body">
                @RenderBody()
            </div>
            <div class="modal-footer">
                <input id="btnSalvar" type="button" value="Salvar" class="btn btn-outline-dark" />
                <input type="button" value="Cancelar" class="btn btn-outline-dark" data-dismiss="modal" />
            </div>        
    </div>
</div>

Project.Web/Views/_navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Navegação">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#"><strong>Conta Fácil</strong></a>
        <div class="collapse navbar-collapse" id="navbarMenu">
            @using Project.Entity
            @{
                Usuario u = (Usuario)Session["Usuario"];
            }
            @if (u != null)
            {
                @Html.Action("PopularMenu", "Menu", new { @menus = u.Perfil.Menus.Where(m => m.IdMenu == null).ToList() })

                <div class="btn-group" role="group">

                    <button id="btnPesquisar" style="display:none" type="button" class="btn btn-lg btn-dark">
                        <i class="fa fa-search"></i>
                    </button>

                    <button id="btnNovo" type="button" style="display:none" class="btn btn-lg btn-dark">
                        <i class="fa fa-plus-square"></i>
                    </button>

                    <button id="btnSalvar" type="button" style="display:none" class="btn btn-lg btn-dark">
                        <i class="fa fa-save"></i>
                    </button>

                    <button id="btnExcluir" type="button" style="display:none" class="btn btn-lg btn-dark">
                        <i class="fa fa-trash"></i>
                    </button>

                    <!--para enxergar a action que está fora da área restrita, foi necessário usar a tag href-->
                    <a href="/Login/Logout" class="btn btn-lg btn-dark">
                        <i class="fa fa-sign-out"></i>
                    </a>


                </div>

            }
        </div>
    </div>
</nav>