Project.Web/Areas/AreaIndex/Controllers/FormaPagamentoController.cs
using System;
using System.Web.Mvc;
using Project.Repository.Persistence;
using System.Linq;
using System.Collections.Generic;
using Project.Web.Areas.AreaIndex.Models;
using Project.Entity;
using Project.Entity.Enuns;

namespace Project.Web.Areas.AreaIndex.Controllers
{
    public class FormaPagamentoController : Controller
    {
        // GET: AreaIndex/FormaPagamento
        public ActionResult ManutencaoFormaPagamento()
        {
            return View();
        }

        public ActionResult Inclusao()
        {
            return View();
        }

        public ActionResult Edicao(int id)
        {
            FormaPagamentoPersistence fpp = new FormaPagamentoPersistence();
            FormaPagamento fp = fpp.ObterPorId(id);

            ViewBag.Id = id;
            ViewBag.Descricao = fp.Descricao;
            ViewBag.Status = fp.Status;

            return View();
        }

        [HttpPost]
        public JsonResult Incluir(string descricao)
        {
            var _cod = -1;
            var _msg = "";

            try
            {
                if (descricao.Trim().Length > 0)
                {
                    FormaPagamentoPersistence fpp = new FormaPagamentoPersistence();

                    if (fpp.ObterPorDescricao(descricao).Count > 0)
                    {
                        _msg = "A Forma de Pagamento " + descricao + " já está cadastrada";
                    }
                    else
                    {

                        fpp.Inserir(new FormaPagamento()
                        {
                            Descricao = descricao
                        });

                        _cod = 1;
                        _msg = "A Forma de Pagamento <strong>" + descricao + "</strong> foi cadastrada com sucesso";
                    }
                }
                else
                {
                    _msg = "A Forma de Pagamento deve ser preenchida";
                }

            }
            catch (Exception ex)
            {
                return Json(new { cod = _cod, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { cod = _cod, msg = _msg }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Editar(FormaPagamentoViewModelEdicao model)
        {
            var _cod = -1;
            var _msg = "";
            try
            {
                FormaPagamentoPersistence fpp = new FormaPagamentoPersistence();

                FormaPagamento fp = fpp.ObterPorId(model.Id);

                fp.Descricao = model.Descricao;
                fp.Status = model.Status;

                fpp.Atualizar(fp);
                _cod = 1;
                _msg = "A Forma de Pagamento <strong>" + model.Descricao + "</strong> foi editada com sucesso!";
            }
            catch (Exception ex)
            {
                _msg = ex.Message;
            }
            return Json(new { cod = _cod, msg = _msg }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Consultar()
        {
            string sBusca = Request.Params["sBusca"].ToString().ToUpper();
            string sStatus = Request.Params["sStatus"].ToString();

            List<FormaPagamentoViewModelConsulta> lista = new List<FormaPagamentoViewModelConsulta>();
            try
            {
                FormaPagamentoPersistence fpp = new FormaPagamentoPersistence();

                foreach (var item in fpp.ListarTodos().ToList())
                {

                    FormaPagamentoViewModelConsulta fp = new FormaPagamentoViewModelConsulta();
                    fp.Id = item.Id;
                    fp.Descricao = item.Descricao;
                    fp.Status = item.Status;

                    if (item.Status.Equals("A"))
                    {
                        fp.DescricaoStatus = Status.A.ObterDescricao();
                    }
                    else if (item.Status.Equals("I"))
                    {
                        fp.DescricaoStatus = Status.I.ObterDescricao();
                    }
                    else
                    {
                        fp.DescricaoStatus = "Valor Desconhecido";
                    }

                    lista.Add(fp);

                };


                if (sBusca.Trim().Length > 0)
                {
                    lista = lista.Where(f => f.Descricao.Trim().ToUpper().Contains(sBusca.Trim().ToUpper())).ToList();
                }
                if ( sStatus.Length >0 && !sStatus.Equals("-1"))
                {
                    lista = lista.Where(f => f.Status.Equals(sStatus)).ToList();
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
            return Json(new
            {
                aaData = lista
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Excluir(int id)
        {
            var msg = "";
            try
            {
                FormaPagamentoPersistence fpp = new FormaPagamentoPersistence();
                FormaPagamento fp = new FormaPagamento();
                fp = fpp.ObterPorId(id);
                fpp.Excluir(fp);

                msg = "A Forma de Pagamento <strong>" + fp.Descricao + "</strong> foi excluída com sucesso!";

            }
            catch (Exception ex)
            {

                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }

            return Json(msg, JsonRequestBehavior.AllowGet);
        }

    }
}

Project.Web/Areas/AreaIndex/Views/FormaPagamento/Edicao.cshtml
<script type="text/javascript">
    var status = "";

    function exibirAlertEdicao(mensagem, tempo) {
        $("#spEdicaoMsg").html(mensagem);
        $("#alertEdicao").show().fadeOut(tempo);//exibe e depois esconde o alert..
    }

    function editar() {

        $.ajax({
            type: "POST",
            url: "/FormaPagamento/Editar",
            //passando o objeto deve estar com os nomes iguais aos dos atributos do método json do Controller
            data: {
                Id: $("#txtId").val(),
                Descricao: $("#txtDescricao").val(),
                Status: $("#cmbStatusEdicao").val()
            },
            success: function (result) {
                //o .msg é identificado como um atributo do retorno da execução..
                //somente com sucesso repopulará a forma de pagamento..
                if (result.cod == 1) {
                    setTimeout(exibirAlertEdicao(result.msg, 10000), 10000);
                    //pegando a tabela que está na página..
                    var tabela = $('#tFormasPagamento').DataTable();
                    //atualizando a tabela na outra página..
                    tabela.ajax.reload();
                } else {
                    exibirAlertEdicao(result.msg, 10000);
                }
            },
            error: function (e) {
                exibirAlertEdicao("Erro: " + e.status);
            }
        });
    }

    $(document).ready(function () {
        $("#spLabel").html("Forma de Pagamento:");
        $("#spTitle").html("Editar Forma de Pagamento");
        PopulaSelectList("Lista", "Status", "#cmbStatusEdicao", $("#txtStatus").val());
    })
</script>
@Html.Partial("~/Views/_edicaoGeneric.cshtml")

Project.Web/Areas/AreaIndex/Views/FormaPagamento/Inclusao.cshtml
<script type="text/javascript">

    function exibirAlertInclusao(mensagem, tempo) {
        $("#spInclusaoMsg").html(mensagem);
        $("#alertInclusao").show().fadeOut(tempo);//exibe e depois esconde o alert..
    }

    function Incluir() {
        var descricao = document.getElementById("txtDescricao").value;
        $.ajax({
            type: "POST",
            url: "/FormaPagamento/Incluir",
            //a variável 'descricao' deve estar com o nome igual ao do parâmetro do método json do Controller
            data: "descricao=" + descricao,
            success: function (result) {
                //o .msg é identificado como um atributo do retorno da execução..
                //somente com sucesso repopulará a forma de pagamento..
                if (result.cod == 1) {
                    setTimeout(exibirAlertInclusao(result.msg, 10000), 10000);
                    //pegando a tabela que está na página..
                    var tabela = $('#tFormasPagamento').DataTable();
                    //atualizando a tabela na outra página..
                    tabela.ajax.reload();
                } else {
                    exibirAlertInclusao(result.msg, 10000);
                }
            },
            error: function (e) {
                exibirAlertInclusao("Erro: " + e.status);
            }
        });
    }

    $(document).ready(function () {
        $("#spLabel").html("Forma de Pagamento:");
        $("#spTitle").html("Incluir Forma de Pagamento");
    })
</script>
@Html.Partial("~/Views/_inclusaoGeneric.cshtml")

Project.Web/Areas/AreaIndex/Views/FormaPagamento/ManutencaoFormaPagamento.cshtml
@{
    ViewBag.Title = "ManutencaoFormaPagamento";
    Layout = "~/Views/_layout.cshtml";
}

<script type="text/javascript">

    var tFormaPagamento = null;

    //chamando o modal de exclusão..
    function del(row) {

        $('#spanConfirmMensagem').html("Deseja excluir a Forma de Pagamento <strong>" + row.Descricao + "</strong>?");

        $('#modalConfirmMensagem').modal({
            backdrop: 'static',
            keyboard: false
        }).one('click', '#btnConfirmSim', function (e) {
            $.ajax({
                type: "POST",
                url: "/FormaPagamento/Excluir",
                data: "id=" + row.Id,
                success: function (result) {
                    exibirAlert(result.msg);
                    $("#btnPesquisar").click();

                },
                error: function (e) {
                    exibirAlert("Erro: " + e.status);
                }
            });

        });
    };

    function edit(id) {
        $("#modal").load("Edicao?id=" + id, function () {
            $("#modal").modal({ backdrop: "static" });
        });

    }

    $(document).ready(function () {
        $("#btnNovo").show();
        $("#btnPesquisar").show();
        $("#btnExcluir").show();

        PopulaSelectList("Lista", "Status", "#cmbStatus", "-1");

        tFormaPagamento = $('#tFormasPagamento').DataTable({
            "bProcessing": false,
            "bServerSide": false,
            "bLengthChange": false, /*tornar invisível combo para visualizar a quantidade de registros */
            "bFilter": false, /*tornar invisível o campo de busca do resultado da tabela */
            "ajax": {
                type: "POST",
                url: "/FormaPagamento/Consultar",
                datatype: "json",
                data: function (d) {
                    d.sBusca = $("#txtBusca").val();
                    d.sStatus = $("#cmbStatus").val();
                },
                error: function (e) {
                    exibirAlert("Erro: " + e.status);
                }
            },
            /*colunas que são utilizadas na dataTable*/
            "aoColumns": [
                { "mData": "Descricao", "sName": "Descricao", "sTitle": "Descrição" },
                { "mData": "DescricaoStatus", "sName": "DescricaoStatus", "sTitle": "Status" },
                {
                    "render": function (data, type, row) {
                        return "<div style='text-align:center'><a href='#' class='btn btn-dark'  onclick=edit('" + row.Id + "')><i class='fa fa-edit'></i></a></div>";
                    }
                },
                {
                    "render": function (data, type, row) {
                        var nome = row.Nome;
                        return "<div style='text-align:center'><button class='btn btn-dark' id='btnExcluir'><i class='fa fa-trash'></i></button></div>";
                    }
                }
            ],
            "columnDefs":
                [{
                    "targets": [0],
                    "width": "50%",
                    "visible": true
                },
                {
                    "targets": [1],
                    "width": "30%",
                    "visible": true
                },
                {
                   "targets": [2],
                   "visible": true,
                   "searchable": false,
                   "orderable": false,
                   "width": "10%"
                },
                {
                    "targets": [3],
                    "visible": true,
                    "searchable": false,
                    "orderable": false,
                    "width": "10%"
                }]
        });

        $("#btnNovo").click(function () {
                $("#modal").load("@Url.Action("Inclusao", "FormaPagamento")", function () {
                    $("#modal").modal({ backdrop:"static"});
                })
        })

        $("#btnPesquisar").click(function () {
            tFormaPagamento.ajax.reload();
            $("#dTFormasPagamento").show();
        })

        $('#tFormasPagamento tbody').on('click', '#btnExcluir', function () {
            var tr = $(this).closest('tr');
            var row = tFormaPagamento.row(tr);
            del(row.data());
        });
    });

    function exibirAlert(mensagem, tempo) {
        $("#spMensagemManutencaoFormaPagamento").html(mensagem);
        $("#alertManutencaoFormaPagamento").show().fadeOut(tempo);//exibe e depois esconde o alert..
    }





</script>

<h5>Forma de Pagamento</h5>
<hr />
<div class="row">
    <div class="col-4">
        <label>Descrição:</label>
        <input type="text" id="txtBusca" class="form-control" />

    </div>

    <div class="col-4">
        <label>Status:</label>
        <select id="cmbStatus" class="form-control"></select>
    </div>
</div>

<div id="dTFormasPagamento" class="row" style="display:none">
    <div class="col-12">
        <table id="tFormasPagamento" class="display" style="width:100%" data-page-length='5'>
            <thead>
                <tr>
                    <th scope="col">Descrição</th>
                    <th scope="col">Status</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

<div id="alertManutencaoFormaPagamento" class="row mt-2" style="display:none">
    <div class="col-12">
        <div class="alert alert-primary" role="alert">
            <span id="spMensagemFormaPagamento"></span>
        </div>
    </div>
</div>

<div id="modal" class="modal" role="dialog">
</div>