Project.Web/Areas/AreaIndex/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Project.Entity;
using Project.Repository.Persistence;
using Project.Entity.Enuns;
using Project.Utility.UtilComboBox;
using Project.Web.Areas.AreaIndex.Models;
using Project.Utility.UtilString;

namespace Project.Web.Areas.AreaIndex.Controllers
{
    [Authorize]
    public class UsuarioController : Controller
    {
        string mensagem = null;

        public ActionResult ManutencaoUsuario()
        {

            return View();
        }

        public ActionResult Inclusao()
        {
            PerfilPersistence pp = new PerfilPersistence();
            ViewBag.ListaPerfis = new SelectList(pp.ListarTodos().ToList(), "Id", "Descricao");
            return View();
        }

        public ActionResult Edicao(string id)
        {

            UsuarioPersistence up = new UsuarioPersistence();
            UsuarioViewModelEdicao model = new UsuarioViewModelEdicao();

            var usuario = up.ObterPorId(id);
            model.Id_Usuario = usuario.IdUsuario;
            model.Nome = usuario.Nome;
            model.Id_Perfil = usuario.IdPerfil;

            PerfilPersistence pp = new PerfilPersistence();
            ViewBag.ListaPerfis = new SelectList(pp.ListarTodos().ToList(), "Id", "Descricao");

            return View(model);
        }

        [HttpPost]
        public JsonResult Consultar()
        {

            //string sSearche = Request.Params["sSearch"].ToString();
            string sBusca =  Request.Params["sBusca"].ToString().ToUpper();
            string sPerfil = Request.Params["sPerfil"].ToString();
            string sStatus = Request.Params["sStatus"].ToString();


            UsuarioPersistence up = new UsuarioPersistence();
            IEnumerable<Usuario> totalUsuarios = up.ListarTodos();
            IList<Usuario> filtroUsuarios = totalUsuarios.ToList<Usuario>();

            if (sBusca != null)
            {
                filtroUsuarios = filtroUsuarios
                    .Where(u =>
                            (u.IdUsuario.ToUpper().Contains(sBusca.ToUpper())) ||
                            (u.Nome.ToString().ToUpper().Contains(sBusca.ToUpper()))
                     ).ToList<Usuario>();
            }

            if (sPerfil != "-1")
            {
                filtroUsuarios = filtroUsuarios
                    .Where(u => u.Perfil.Id.ToString().Contains(sPerfil.ToUpper())
                     ).ToList<Usuario>();
            }

            if (sStatus != "-1")
            {
                filtroUsuarios = filtroUsuarios
                    .Where(u => u.Status.ToString().Contains(sStatus.ToUpper())
                     ).ToList<Usuario>();
            }

            List<UsuarioViewModelConsulta> lista = new List<UsuarioViewModelConsulta>();

            foreach (var item in filtroUsuarios)
            {
                UsuarioViewModelConsulta u = new UsuarioViewModelConsulta();
                u.IdUsuario = item.IdUsuario;
                u.Nome = item.Nome;
                u.Perfil = item.Perfil.Descricao;
                u.Status = item.Status;

                lista.Add(u);
            }

            var Resultado = new
            {
                aaData = lista
            };

            return Json(Resultado, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Incluir(UsuarioViewModelInclusao usuarioModel)
        {

            try
            {

                if (ModelState.IsValid)
                {
                    UsuarioPersistence up = new UsuarioPersistence();

                    if (up.LoginExistente(usuarioModel.Id_Usuario) > 0)
                    {
                        mensagem = "O Login informado já existe";
                    }
                    else
                    {

                        Usuario u = new Usuario();

                        u.IdUsuario = usuarioModel.Id_Usuario;
                        u.Nome = usuarioModel.Nome;
                        u.Senha = Criptografia.EncriptarSenha("ABC123");
                        u.IdPerfil = usuarioModel.Id_Perfil;

                        up.Inserir(u);
                        mensagem = $"Os dados do usuário {usuarioModel.Nome} foram gravados com sucesso!";
                    }
                }
            }
            catch (Exception ex)
            {
                mensagem = ex.Message.ToString();
            }

            return Json(new { msg = mensagem });
        }

        [HttpPost]
        public JsonResult Editar(UsuarioViewModelEdicao usuarioModel)
        {

            try
            {

                if (ModelState.IsValid)
                {
                    UsuarioPersistence up = new UsuarioPersistence();
                    Usuario u = up.ObterPorId(usuarioModel.Id_Usuario);

                    u.Nome = usuarioModel.Nome;
                    u.IdPerfil = usuarioModel.Id_Perfil;

                    if (usuarioModel.RedefinirSenha)
                    {
                        u.Senha = Criptografia.EncriptarSenha("ABC123");
                    }

                    up.Atualizar(u);
                    mensagem = $"Os dados do usuário {usuarioModel.Nome} foram editados com sucesso!";

               }
            }
            catch (Exception ex)
            {
                return Json(new { msg = ex.Message.ToString() });

            }

            return Json(new { msg = mensagem });
        }

        [HttpPost]
        public JsonResult Excluir(string id)
        {

            try
            {
                    UsuarioPersistence up = new UsuarioPersistence();
                    Usuario u = up.ObterPorId(id);

                    up.Excluir(u);
                    mensagem = $"Os dados do usuário {u.Nome} foram excluídos com sucesso!";                
            }
            catch (Exception ex)
            {
                return Json(new { msg = ex.Message.ToString() });

            }

            return Json(new { msg = mensagem });
        }

    }
}

Project.Web/Areas/AreaIndex/Views/Usuario/Edicao.cshtml
@model Project.Web.Areas.AreaIndex.Models.UsuarioViewModelEdicao
@{
    ViewBag.Title = "Usuário";
}

<script src="~/js/jquery.unobtrusive-ajax.min.js"></script>

<!--Para que a validação do MVC funcione, foi necessário colocar a referência deste script-->
<script src="~/js/jquery.validate.unobtrusive.min.js"></script>


<script type="text/javascript">
    function OnFailure(result) {
        alert("Erro:" + result.msg);
    }

    function OnSuccess(result) {

        //Como o modal é renderizado dentro da página de ConsultaFiltro.cshntm,
        // pode-se pegar o handle da tabela que já está criada no ConsultaFiltro...
        // e aplicar a atualização da table..
        var tabela = $('#tabela').DataTable();
        tabela.ajax.reload();

        //exibindo a mensagem na tela de consulta..
        //isso pode ser feito porque a tela de edição é renderizada na tela de consulta..
        $("#mensagem").html(result.msg);
        $("#alert").show().fadeOut(8000);//exibe e depois esconde o alert..


        //fechando o modal..
        $(".close").click();

    }
</script>

<div id="modal_dialog" class="modal-dialog">
    <div class="modal-content">
        @using (Ajax.BeginForm("Editar", "Usuario", new AjaxOptions()
        {
            HttpMethod = "POST",
            OnFailure = "OnFailure",
            OnSuccess = "OnSuccess"
        })
               )
        {
            <div class="modal-header">
                <h5 class="modal-title">Editar Usuário</h5>

                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                    <span class="sr-only">Close</span>
                </button>

            </div>
            <div class="modal-body">


                @Html.ValidationSummary(true)


                <div class="row">
                    <div class="form-group mb-1 col-12">
                        @Html.LabelFor(model => model.Id_Usuario)

                        @Html.TextBoxFor(model => model.Id_Usuario, new { @class = "form-control", @placehoder = "Informe a chave" })
                        <span style="color:red">
                            @Html.ValidationMessageFor(model => model.Id_Usuario)
                        </span>

                    </div>

                    <div class="form-group mb-1 col-12">
                        @Html.LabelFor(model => model.Nome)

                        @Html.TextBoxFor(model => model.Nome, new { @class = "form-control", @placehoder = "Informe o nome" })
                        <span style="color:red">
                            @Html.ValidationMessageFor(model => model.Nome)
                        </span>

                    </div>

                    <div class="form-group mb-1 col-12">
                        @Html.LabelFor(model => model.Id_Perfil)

                        @Html.DropDownListFor(model => model.Id_Perfil, (SelectList)ViewBag.ListaPerfis, "--Selecione--", new { @class = "form-control " })
                        <span style="color:red">
                            @Html.ValidationMessageFor(model => model.Id_Perfil)
                        </span>

                    </div>

                    <div class="form-check mb-1 mt-3 col-12">

                        @Html.CheckBox("RedefinirSenha", false)
                        @Html.LabelFor(model => model.RedefinirSenha)

                    </div>

                </div>

            </div>
            <div class="modal-footer">
                <input type="submit" value="Salvar" class="btn btn-outline-dark" />
                <input type="button" value="Cancelar" class="btn btn-outline-dark" data-dismiss="modal" />
            </div>

        }

    </div>
</div>

Project.Web/Areas/AreaIndex/Views/Usuario/Inclusao.cshtml
@model Project.Web.Areas.AreaIndex.Models.UsuarioViewModelInclusao
@{
    ViewBag.Title = "Usuário";
}
<!--Para que a validação do MVC funcione, foi necessário colocar a referência deste script-->
<script src="~/js/jquery.validate.unobtrusive.min.js"></script>

<script type="text/javascript">
    function OnFailure(result) {
        //adicionar mensagem igual a da edição..
        alert("Erro:" + result.msg);
    }

    function OnSuccess(result) {

        //Como o modal é renderizado dentro da página de ConsultaFiltro.cshntm,
        // pode-se pegar o handle da tabela que já está criada no ConsultaFiltro...
        // e aplicar a atualização da table..
        var tabela = $('#tabela').DataTable();
        tabela.ajax.reload();

        $("#mensagemInclusao").html(result.msg);
        $("#alertInclusao").show();

    }
</script>

<div class="modal-dialog">
    <div class="modal-content">
        @using (Ajax.BeginForm("Incluir", "Usuario", new AjaxOptions()
        {
            HttpMethod = "POST",
            OnFailure = "OnFailure",
            OnSuccess = "OnSuccess"
        })
               )
        {
            <div class="modal-header">
                <h5 class="modal-title">Incluir Usuário</h5>

                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                    <span class="sr-only">Close</span>
                </button>

            </div>
            <div class="modal-body">


                <div id="alertInclusao" class="alert alert-primary" style="display:none">
                    <span id="mensagemInclusao"></span>
                </div>


                @Html.ValidationSummary(true)


                <div class="row">
                    <div class="form-group mb-1 col-12">
                        @Html.LabelFor(model => model.Id_Usuario)

                        @Html.TextBoxFor(model => model.Id_Usuario, new { @class = "form-control", @placehoder = "Informe a chave" })
                        <span style="color:red">
                            @Html.ValidationMessageFor(model => model.Id_Usuario)
                        </span>

                    </div>

                    <div class="form-group mb-1 col-12">
                        @Html.LabelFor(model => model.Nome)

                        @Html.TextBoxFor(model => model.Nome, new { @class = "form-control", @placehoder = "Informe o nome" })
                        <span style="color:red">
                            @Html.ValidationMessageFor(model => model.Nome)
                        </span>

                    </div>

                    <div class="form-group mb-1 col-12">
                        @Html.LabelFor(model => model.Id_Perfil)

                        @Html.DropDownListFor(model => model.Id_Perfil, (SelectList)ViewBag.ListaPerfis, "--Selecione--", new { @class = "form-control " })
                        <span style="color:red">
                            @Html.ValidationMessageFor(model => model.Id_Perfil)
                        </span>

                    </div>

                    @*<div class="form-group mb-1 col-6">
                            @Html.LabelFor(model => model.Senha)

                            @Html.PasswordFor(model => model.Senha, new { @class = "form-control", @placehoder = "Informe a senha" })
                            <span style="color:red">
                                @Html.ValidationMessageFor(model => model.Senha)
                            </span>

                        </div>

                        <div class="form-group mb-1 col-6">
                            @Html.LabelFor(model => model.ConfirmaSenha)

                            @Html.PasswordFor(model => model.ConfirmaSenha, new { @class = "form-control", @placehoder = "Confirme a senha" })
                            <span style="color:red">
                                @Html.ValidationMessageFor(model => model.ConfirmaSenha)
                            </span>

                        </div>*@
                </div>

            </div>
            <div class="modal-footer">
                <input type="submit" value="Salvar" class="btn btn-outline-dark" />
                <input type="button" value="Cancelar" class="btn btn-outline-dark" data-dismiss="modal" />
            </div>

        }

    </div>
</div>

Project.Web/Areas/AreaIndex/Views/Usuario/ManutencaoUsuario.cshtml
@*@model List<Project.Web.Areas.AreaIndex.Models.MenuPerfilViewModelConsulta>*@

@{
    ViewBag.Title = "Consulta Usuários";
    Layout = "~/Views/_layout.cshtml";
}



<script type="text/javascript">

    //chamando o modal de inclusão..
    $("#btnNovo").click(function () {
        $("#modal").load("Inclusao", function () {
            $("#modal").modal({ backdrop: "static" });
        });
    });

    //chamando o modal de edição..
    function edit(id) {
        $("#modal").load("Edicao?id=" + id, function () {
            $("#modal").modal({ backdrop: "static" });
        });
    };

    //chamando o modal de exclusão..
    function del(id) {

        $('#spanConfirmMensagem').html("Deseja excluir o usuário <strong>" + id + "</strong>?");

        $('#modalConfirmMensagem').modal({
            backdrop: 'static',
            keyboard: false
        }).one('click', '#btnConfirmSim', function (e) {
            $.ajax({
                type: "POST",
                url: "/Usuario/Excluir",
                data: "id=" + id,
                success: function (result) {
                    exibirAlert(result.msg);
                    $("#btnPesquisar").click();

                },
                error: function (e) {
                    exibirAlert("Erro: " + e.status);
                }
            });

       });
    };

    function exibirAlert(mensagem) {
        $("#mensagem").html(mensagem);
        $("#alert").show().fadeOut(8000);//exibe e depois esconde o alert..
    }

    $(document).ready(function () {

        $("#btnNovo").show();
        $("#btnPesquisar").show();


        PopulaSelectList("Lista", "Perfil","#cmbPerfil", "-1");
        PopulaSelectList("Lista", "Status","#cmbStatus", "-1");

        var table = $('#tabela').DataTable({
            "bProcessing": false,
            "bServerSide": false,
            "bLengthChange": false, /*tornar invisível combo para visualizar a quantidade de registros */
            "bFilter": false, /*tornar invisível o campo de busca do resultado da tabela */
            "ajax": {
                type: "POST",
                url: "/Usuario/Consultar",
                datatype: "json",
                data: function (d) {
                    d.sBusca = $("#txtBusca").val();
                    d.sPerfil = $("#cmbPerfil").val();
                    d.sStatus = $("#cmbStatus").val();
                },
                error: function (e) {
                    exibirAlert("Erro: " + e.status);
                }
            },

            /*colunas que são utilizadas na dataTable*/
            "aoColumns": [
                { "mData": "IdUsuario", "sName": "IdUsuario", "sTitle": "Login" },
                { "mData": "Nome", "sName": "Nome", "sTitle": "Nome" },
                { "mData": "Perfil", "sName": "Perfil", "sTitle": "Perfil" },
                { "mData": "Status", "sName": "Status", "sTitle": "Status" },
                {
                    "render": function (data, type, row) {
                        return "<div style='text-align:center'><a href='#' class='btn btn-dark'  onclick=edit('" + row.IdUsuario + "')><i class='fa fa-edit'></i></a></div>";
                    }
                },
                {
                    "render": function (data, type, row) {
                        var nome = row.Nome;
                        return "<div style='text-align:center'><button class='btn btn-dark'  onclick=del('" + row.IdUsuario + "')><i class='fa fa-trash'></i></button></div>";
                    }
                }
            ],
            "columnDefs":
                [{
                    "targets": [4],
                    "visible": true,
                    "searchable": false,
                    "orderable": false
                },
                {
                    "targets": [5],
                    "visible": true,
                    "searchable": false,
                    "orderable": false
                }]
        });

        //botão pesquisar..
        $("#btnPesquisar").click(function () {
            //atualiza a table para uma nova pesquisa..
            table.ajax.reload();
            $("#TabelaUsuarios").show();
        });



    });

</script>

<h5>Usuários</h5>
<hr />

<div class="row">
    <div class="col-4">
        <label>Nome ou Chave:</label>
        <input type="text" id="txtBusca" class="form-control" />

    </div>
    <div class="col-3">
        <label>Perfil:</label>
        <select id="cmbPerfil" class="form-control"></select>
    </div>

    <div class="col-3">
        <label>Status:</label>
        <select id="cmbStatus" class="form-control"></select>
    </div>

</div>

<div id="TabelaUsuarios" class="row mt-3" style="display:none">
    <div class="col-12">
        <table id="tabela" class="display" style="width:100%" data-page-length='5'>
            <thead>
                <tr>
                    <th scope="col">Usuário</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Perfil</th>
                    <th scope="col">Status</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody id="bodyTable"></tbody>
        </table>
    </div>
</div>

<div id="alert" class="row mt-2" style="display:none">

    <div class="col-12">
        <div class="alert alert-primary" role="alert">
            <span id="mensagem"></span>
        </div>
    </div>

</div>

<div class="modal" id="modal" role="dialog">
</div>