Project.Web/Areas/AreaIndex/Controllers/ContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Project.Web.Areas.AreaIndex.Models;
using Project.Repository.Persistence;
using Project.Entity.Enuns;
using Project.Entity;

namespace Project.Web.Areas.AreaIndex.Controllers
{
    public class ContaController : Controller
    {
        // GET: AreaIndex/Conta
        public ActionResult ManutencaoConta()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Consultar()
        {
            string sBusca = Request.Params["sBusca"].ToString().ToUpper();
            string sStatus = Request.Params["sStatus"].ToString().ToUpper();

            List<ContaViewModelConsulta> lista = new List<ContaViewModelConsulta>();
            try
            {
                ContaPersistence cp = new ContaPersistence();
                foreach (var item in cp.ListarTodos())
                {
                    ContaViewModelConsulta model = new ContaViewModelConsulta();
                    model.Id = item.Id;
                    model.Descricao = item.Descricao;
                    model.Status = item.Status;


                    if (item.Status.Equals("A"))
                    {
                        model.DescricaoStatus = Status.A.ObterDescricao();
                    }
                    else if (item.Status.Equals("I"))
                    {
                        model.DescricaoStatus = Status.I.ObterDescricao();
                    }
                    else
                    {
                        model.DescricaoStatus = "Valor Desconhecido";
                    }

                    lista.Add(model);

                    if (sBusca.Trim().Length > 0)
                    {
                        lista = lista.Where(c => c.Descricao.Trim().ToUpper().Contains(sBusca.Trim().ToUpper())).ToList();
                    }
                    if (sStatus.Length > 0 && !sStatus.Equals("-1"))
                    {
                        lista = lista.Where(f => f.Status.Equals(sStatus)).ToList();
                    }

                }
            }
            catch (Exception ex)
            {

                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }

            return Json(new { aaData = lista }, JsonRequestBehavior.AllowGet);
        }

        
        public ActionResult Inclusao()
        {
            return View();
        }

        public ActionResult Edicao( int id)
        {
            try
            {
                ContaPersistence cp = new ContaPersistence();
                Conta c = cp.ObterPorId(id);

                ViewBag.Id = c.Id;
                ViewBag.Descricao = c.Descricao;
                ViewBag.Status = c.Status;
            }
            catch (Exception)
            {

                throw;
            }

            return View();
        }

        [HttpPost]
        public JsonResult Incluir(string descricao)
        {
            var _cod = -1;
            var _msg = "";

            try
            {
                if (descricao.Trim().Length > 0)
                {
                    ContaPersistence cp = new ContaPersistence();

                    if (cp.ObterPorDescricao(descricao).Count > 0)
                    {
                        _msg = "A Conta " + descricao + " já está cadastrada";
                    }
                    else
                    {

                        cp.Inserir(new Conta()
                        {
                            Descricao = descricao
                        });

                        _cod = 1;
                        _msg = "A Conta <strong>" + descricao + "</strong> foi cadastrada com sucesso";
                    }
                }
                else
                {
                    _msg = "A Conta deve ser preenchida";
                }

            }
            catch (Exception ex)
            {
                return Json(new { cod = _cod, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { cod = _cod, msg = _msg }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Excluir(int id)
        {
            var msg = "";
            try
            {
                ContaPersistence cp = new ContaPersistence();
                Conta c = new Conta();
                c = cp.ObterPorId(id);
                cp.Excluir(c);

                msg = "A Conta <strong>" + c.Descricao + "</strong> foi excluída com sucesso!";

            }
            catch (Exception ex)
            {

                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }

            return Json(msg, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Editar(ContaViewModelEdicao model)
        {
            var _cod = -1;
            var _msg = "";
            try
            {
                ContaPersistence cp = new ContaPersistence();

                Conta c = cp.ObterPorId(model.Id);

                c.Descricao = model.Descricao;
                c.Status = model.Status;

                cp.Atualizar(c);
                _cod = 1;
                _msg = "A Conta <strong>" + model.Descricao + "</strong> foi editada com sucesso!";
            }
            catch (Exception ex)
            {
                _msg = ex.Message;
            }
            return Json(new { cod = _cod, msg = _msg }, JsonRequestBehavior.AllowGet);
        }
    }
}

Project.Web/Areas/AreaIndex/Views/Conta/Edicao.cshtml
<script type="text/javascript">
    var status = "";

    function exibirAlertEdicao(mensagem, tempo) {
        $("#spEdicaoMsg").html(mensagem);
        $("#alertEdicao").show().fadeOut(tempo);//exibe e depois esconde o alert..
    }

    function editar() {

        $.ajax({
            type: "POST",
            url: "/Conta/Editar",
            //passando o objeto deve estar com os nomes iguais aos dos atributos do método json do Controller
            data: {
                Id: $("#txtId").val(),
                Descricao: $("#txtDescricao").val(),
                Status: $("#cmbStatusEdicao").val()
            },
            success: function (result) {
                //o .msg é identificado como um atributo do retorno da execução..
                //somente com sucesso repopulará a forma de pagamento..
                if (result.cod == 1) {
                    setTimeout(exibirAlertEdicao(result.msg, 10000), 10000);
                    //pegando a tabela que está na página..
                    var tabela = $('#tContas').DataTable();
                    //atualizando a tabela na outra página..
                    tabela.ajax.reload();
                } else {
                    exibirAlertEdicao(result.msg, 10000);
                }
            },
            error: function (e) {
                exibirAlertEdicao("Erro: " + e.status);
            }
        });
    }

    $(document).ready(function () {
        $("#spLabel").html("Conta:");
        $("#spTitle").html("Editar Conta");
        PopulaSelectList("Lista", "Status", "#cmbStatusEdicao", $("#txtStatus").val());
    })
</script>
@Html.Partial("~/Views/_edicaoGeneric.cshtml")

Project.Web/Areas/AreaIndex/Views/Conta/Inclusao.cshtml
<script type="text/javascript">

    function exibirAlertInclusao(mensagem, tempo) {
        $("#spInclusaoMsg").html(mensagem);
        $("#alertInclusao").show().fadeOut(tempo);//exibe e depois esconde o alert..
    }

    function Incluir() {
        var descricao = document.getElementById("txtDescricao").value;
        $.ajax({
            type: "POST",
            url: "/Conta/Incluir",
            //a variável 'descricao' deve estar com o nome igual ao do parâmetro do método json do Controller
            data: "descricao=" + descricao,
            success: function (result) {
                //o .msg é identificado como um atributo do retorno da execução..
                //somente com sucesso repopulará a forma de pagamento..
                if (result.cod == 1) {
                    setTimeout(exibirAlertInclusao(result.msg, 10000), 10000);
                    //pegando a tabela que está na página..
                    var tabela = $('#tContas').DataTable();
                    //atualizando a tabela na outra página..
                    tabela.ajax.reload();
                } else {
                    exibirAlertInclusao(result.msg, 10000);
                }
            },
            error: function (e) {
                exibirAlertInclusao("Erro: " + e.status);
            }
        });
    }

    $(document).ready(function () {
        $("#spLabel").html("Conta:");
        $("#spTitle").html("Incluir Conta");
    })
</script>
@Html.Partial("~/Views/_inclusaoGeneric.cshtml")

Project.Web/Areas/AreaIndex/Views/Conta/ManutencaoConta.cshtml
@{
    ViewBag.Title = "ManutencaoConta";
    Layout = "~/Views/_layout.cshtml";
}

<script type="text/javascript">

    var tConta = null;

    //chamando o modal de exclusão..
    function del(row) {

        $('#spanConfirmMensagem').html("Deseja excluir a conta <strong>" + row.Descricao + "</strong>?");

        $('#modalConfirmMensagem').modal({
            backdrop: 'static',
            keyboard: false
        }).one('click', '#btnConfirmSim', function (e) {
            $.ajax({
                type: "POST",
                url: "/Conta/Excluir",
                data: "id=" + row.Id,
                success: function (result) {
                    exibirAlert(result.msg);
                    $("#btnPesquisar").click();

                },
                error: function (e) {
                    exibirAlert("Erro: " + e.status);
                }
            });

        });
    };

    function edit(id) {
        $("#modal").load("Edicao?id=" + id, function () {
            $("#modal").modal({ backdrop: "static" });
        });

    }

    $(document).ready(function () {
        $("#btnNovo").show();
        $("#btnPesquisar").show();
        $("#btnExcluir").show();

        PopulaSelectList("Lista", "Status", "#cmbStatus", "-1");

        tConta = $('#tContas').DataTable({
            "bProcessing": false,
            "bServerSide": false,
            "bLengthChange": false, /*tornar invisível combo para visualizar a quantidade de registros */
            "bFilter": false, /*tornar invisível o campo de busca do resultado da tabela */
            "ajax": {
                type: "POST",
                url: "/Conta/Consultar",
                datatype: "json",
                data: function (d) {
                    d.sBusca = $("#txtBusca").val();
                    d.sStatus = $("#cmbStatus").val();
                },
                error: function (e) {
                    exibirAlert("Erro: " + e.status);
                }
            },
            /*colunas que são utilizadas na dataTable*/
            "aoColumns": [
                { "mData": "Descricao", "sName": "Descricao", "sTitle": "Descrição" },
                { "mData": "DescricaoStatus", "sName": "DescricaoStatus", "sTitle": "Status" },
                {
                    "render": function (data, type, row) {
                        return "<div style='text-align:center'><a href='#' class='btn btn-dark'  onclick=edit('" + row.Id + "')><i class='fa fa-edit'></i></a></div>";
                    }
                },
                {
                    "render": function (data, type, row) {
                        var nome = row.Nome;
                        return "<div style='text-align:center'><button class='btn btn-dark' id='btnExcluir'><i class='fa fa-trash'></i></button></div>";
                    }
                }
            ],
            "columnDefs":
                [{
                    "targets": [0],
                    "width": "50%",
                    "visible": true
                },
                {
                    "targets": [1],
                    "width": "30%",
                    "visible": true
                },
                {
                   "targets": [2],
                   "visible": true,
                   "searchable": false,
                   "orderable": false,
                   "width": "10%"
                },
                {
                    "targets": [3],
                    "visible": true,
                    "searchable": false,
                    "orderable": false,
                    "width": "10%"
                }]
        });

        $("#btnNovo").click(function () {
                $("#modal").load("@Url.Action("Inclusao", "Conta")", function () {
                    $("#modal").modal({ backdrop:"static"});
                })
        })

        $("#btnPesquisar").click(function () {
            tConta.ajax.reload();
            $("#dTContas").show();
        })

        $('#tContas tbody').on('click', '#btnExcluir', function () {
            var tr = $(this).closest('tr');
            var row = tConta.row(tr);
            del(row.data());
        });
    });

    function exibirAlert(mensagem, tempo) {
        $("#spMensagemConta").html(mensagem);
        $("#alertManutencaoConta").show().fadeOut(tempo);//exibe e depois esconde o alert..
    }

</script>


<h5>Conta</h5>
<hr />
<div class="row">
    <div class="col-4">
        <label>Descrição:</label>
        <input type="text" id="txtBusca" class="form-control" />

    </div>

    <div class="col-4">
        <label>Status:</label>
        <select id="cmbStatus" class="form-control"></select>
    </div>
</div>

<div id="dTContas" class="row" style="display:none">
    <div class="col-12">
        <table id="tContas" class="display" style="width:100%" data-page-length='5'>
            <thead>
                <tr>
                    <th scope="col">Descrição</th>
                    <th scope="col">Status</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

<div id="alertManutencaoConta" class="row mt-2" style="display:none">
    <div class="col-12">
        <div class="alert alert-primary" role="alert">
            <span id="spMensagemConta"></span>
        </div>
    </div>
</div>

<div id="modal" class="modal" role="dialog">
</div>